### ISSUE TITLE
Need a threshold adjustment all of a users' votes get eliminated

### ISSUE THREAD

**Issue by lbeitzel** [XandalfTheGray/book-vote-bot#2]
Once all of the books that a user votes for are eliminated, that user should no longer be kept in the threshold calculation, since they are unable to contribute any more votes.

This is easily fixed by moving the threshold calculation from the start of `ranked_vote_verbose()` to the start of the main loop.

**Comment by XandalfTheGray** [comment]
Threshold not used in current iteration

**Comment by XandalfTheGray** [comment]
Closing

**Comment by XandalfTheGray** [comment]
Threshold not used in current iteration
