### ISSUE TITLE
Investigate if vote_table needs to be reexamined

### ISSUE THREAD

**Issue by lbeitzel** [XandalfTheGray/book-vote-bot#3]
I'm not sure 100% if this is an issue or not, but reading through the code it seems like `vote_table` doesn't always reflect the later rounds of voting properly. After a book is eliminated, the `win_counter` is updated, but I think the `vote_table` also needs to be updated.

**Comment by lbeitzel** [comment]
Example: in the third round of `test-case1`, book A is luckily picked, but that is just by luck because based on the `vote_table`, all of the books are equivalent, even though book A has the least amount of `win_counter` votes.

I think we should count the votes that are brought over from eliminated books as 1st place votes, and should update the `vote_table` accordingly.

**Comment by XandalfTheGray** [comment]
@lbeitzel Hopping on later to get a better look at this, but the 4th index in the vote_table for each book is the win_counter, that’s the only aspect that was meant to change. In the first 3 indexes it’s meant to hold the number of 1st, 2nd, and 3rd place votes for those books, respectively.

That was unclear in my initial comments, looking back. Do you think that is a solid way to do this? Also, if you think there’s anywhere vote_table is not working as outlined about let me know.

**Comment by XandalfTheGray** [comment]
Vote Table removed in our new, more IRV-focused script.
